setw -g mode-keys vi

set -g default-terminal "xterm-256color" #x11 specific
set-option -ga terminal-overrides ",xterm-256color:Tc" #x11 specific
set -g status-bg "#1e1e2e"
set -g status-fg "#cdd6f4"

set -g mouse on
set -sg escape-time 0
set -g pane-active-border-style fg="#fab387"
set -g pane-border-style fg="#313244"
